project:
  type: book

book:
  title: "Detección de cuentas falsas de Instagram"
  author: "Eulogio Quemada Torres"
  date: "2024-05-26"
  chapters:
    - index.qmd
    - exploratory_analysis.qmd
    - data_visualization.qmd
    - association_rules.qmd
    - formal_concept_analysis.qmd
    - regression.qmd
    - temporal_series.qmd
    - other_techniques.qmd
    - predictor.qmd
    - summary.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

