# Introducción

Este libro ha sido escrito por Eulogio Quemada Torres, alumno de Laboratorio de Computación Cíentífica como asignatura optativa en el grado de Ingeniería del Software, impartida por el profesor Ángel Mora Bonilla.

El propósito del mismo es analizar los datos propuestos en el dataset de [Kaggle](https://www.kaggle.com/code/durgeshrao9993/fake-instagram-profile-detection-model/input?select=train.csv). Este dataset contiene información sobre distintas cuentas de Instagram y si son falsas o reales.

Antes de comenzar vamos a describir las distintas variables que tenemos en nuestro dataset. Será de vital importancia entender el significado cada una para poder seguir el hilo de las técnicas de análisis de datos que se aplicarán durante este libro.

## Variables

### profile pic

Indica si la cuenta tiene foto de perfil o no. Los usuarios nuevos por defecto no tienen ninguna foto de perfil, lo que las cuentas falsas puede que luego no usen.

### nums/length username

Es la proporción de números sobre la longitud total de carácteres en el nombre de usuario. Ciertas cuentas reales tienen algún número en la cuenta, algunos su día de nacimiento, su año, algún número que les guste. Pero tener muchos números puede ser algo raro.

### fullname words

Número de palabras en el nombre completo. Un nombre de una persona europea suele tener 2 o 3 palabras, en función de los apellidos, algunos más, algunos menos, pero cercano a esto.

### nums/length fullname

Es la proporción de números sobre la longitud del nombre completo. Un nombre de persona, en la mayoría de países del mundo, no puede tener números, así que la presencia de estos puede ser indicativo de que algo está pasando.

### name==username

Indica si el nombre de usuario y el nombre real de la cuenta es el mismo. No es lo normal que sea exactamente el mismo, puede ser indicativo de algo extraño.

### description length

Representa el número de carácteres en la descripción de la cuenta de Instagram.

### external URL

Indica si la cuenta tiene un enlace externo o no, en su perfil.

### private

Indica si la cuenta es privada o no.

### posts

Número de publicaciones realizadas por la cuenta de Instagram.

### followers

Número de seguidores de la cuenta de Instagram.

### follows

Número de personas a las que sigue la cuenta de Instagram.

### fake

Es la clasificación. Un 1 para las cuentas clasificadas como falsas, un 0 para las reales.

## Próximos pasos

Durante este libro intentaremos aplicar las técnicas aprendidas en la asignatura para el análisis de datos. Algunas técnicas pueden que no sean aplicables, otras pueden ser mejores o peores, pero intentaremos extraer conocimiento de los datos y sacar conclusiones interesantes.
