# Predictor interactivo

Con la regresión, obtuvimos un buen modelo capaz de predecir si una cuenta de Instagram es falsa o no. Nuestro **modelo5** daba muy buenos resultados.

Dado que es un modelo de regresión, lo que estamos haciendo es aplicar una fórmula matemática a nuestros datos, que nos da un resultado númerico. Este luego lo estamos binarizando y en función de si es 0 o 1 sabemos si la cuenta es real o falsa.

Podemos implementar fácilmente dicho modelo usando JavaScript, lo que nos permite incrustar en este apartado de nuestro libro de Quarto un formulario interactivo que nos permita predecir si una cuenta es real o falsa.

-   **¿Por qué hacerlo con HTML y JavaScript si tenemos R Shiny?**

R Shiny necesita de un servidor para poder estar ejecutando el código R. Un navegador no ejecuta código R. Como no podemos ejecutar código R, podemos construir una página e implementar la formula de nuestro modelo. Eso es justamente lo que hemos hecho.

En un principio comenzamos a desarrollar este apartado de forma que solo introduciendo el nombre de usuario de Instagram de la persona, te realizaba la predicción, pero lamentablemente, la API para obtener datos de un perfil de usuario de Instagram es limitada actualmente.

A continuación, puedes introducir los datos references a la cuenta de Instagram que desees, y al pulsar el botón **Predecir cuenta** obtendrás una predicción de si la cuenta que has introducido es real o falsa.

```{=html}
<style>
  h2 {
    margin-bottom: 20px;
  }

  .form-group {
    display: flex;
    align-items: center;
    margin-bottom: 15px;
  }

  .form-group label {
    flex: 1;
    margin-right: 10px;
  }

  .form-group input[type="number"],
  .form-group input[type="text"],
  .form-group input[type="textarea"],
  .form-group input[type="checkbox"] {
    flex: 1;
  }

  #miBoton {
    display: block;
    width: 100%;
    padding: 10px;
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    text-align: center;
  }

  #miBoton:hover {
    background-color: #0056b3;
  }

  #resultado {
    margin-top: 20px;
    padding-top: 1px;
    padding-bottom: 14px;
    background: #e9ecef;
    border-radius: 4px;
    text-align: center;
    font-weight: bold;
  }
</style>

<div class="container">
  <h2>Introduce los datos de la cuenta:</h2>
  <div class="form-group">
    <label for="username">Nombre de usuario de la cuenta</label>
    <input class="form-control" type="text" id="username">
  </div>
  <div class="form-group">
    <label for="realname">Nombre real</label>
    <input class="form-control" type="text" id="realname">
  </div>
  <div class="form-group">
    <label for="descriptionLength">Descripción (Copia y pega)</label>
    <input class="form-control" type="textarea" id="descriptionLength">
  </div>
  <div class="form-group">
    <label for="XPosts">Número de publicaciones</label>
    <input class="form-control" type="number" id="XPosts">
  </div>
  <div class="form-group">
    <label for="XFollowers">Número de seguidores</label>
    <input class="form-control" type="number" id="XFollowers">
  </div>
  <div class="form-group">
    <label for="XFollows">Número de seguidos</label>
    <input class="form-control" type="number" id="XFollows">
  </div>
  <div class="form-group">
    <label for="profilePic">¿Foto de perfil?</label>
    <input type="checkbox" id="profilePicCheckbox">
  </div>
  <div class="form-group">
    <label for="externalURL">¿Tiene enlace externo?</label>
    <input type="checkbox" id="externalURLCheckbox">
  </div>
  <div class="form-group">
    <label for="private">¿La cuenta es privada?</label>
    <input type="checkbox" id="privateCheckbox">
  </div>
  <button type="button" id="miBoton">Predecir cuenta</button>
  <div id="resultado"></div>
</div>

<script>
  function predecirCuenta() {
    const username = document.getElementById("username").value;
    const realname = document.getElementById("realname").value;
    const descriptionLength = parseFloat(document.getElementById("descriptionLength").value.length);
    const XPosts = document.getElementById("XPosts").value;
    const XFollowers = parseFloat(document.getElementById("XFollowers").value);
    const XFollows = parseFloat(document.getElementById("XFollows").value);

    const profilePic = document.getElementById("profilePicCheckbox").checked ? 1 : 0;
    const externalURL = document.getElementById("externalURLCheckbox").checked ? 1 : 0;
    const private = document.getElementById("privateCheckbox").checked ? 1 : 0;

    if (username.length === 0) {
      document.getElementById("resultado").innerHTML = "<h3 style='color: red;'>El nombre de usuario es obligatorio</h3>";
    } else {
      let numeros = 0;
      for (let i = 0; i < username.length; i++) {
          if (!isNaN(parseInt(username[i])))
              numeros++;
      }
  
      const numsLengthUsername = numeros / username.length;
      const nameUsername = username === realname ? 1 : 0;
  
      const intercept = 8.893e-01;
      const coef_profilePic = -2.612e-01;
      const coef_numsLengthUsername = 5.798e-01;
      const coef_nameUsername = 1.179e-01;
      const coef_descriptionLength = -1.087e-02;
      const coef_externalURL = -6.688e-02;
      const coef_descriptionLength2 = 2.864e-04;
      const coef_descriptionLength3 = -3.118e-06;
      const coef_descriptionLength4 = 1.150e-08;
      const coef_logXFollowers = 1.934e-01;
      const coef_logXFollowers2 = -9.358e-02;
      const coef_logXFollowers3 = 9.707e-03;
      const coef_logXFollowers4 = -2.979e-04;
      const coef_XFollows05 = 4.795e-03;
  
      const logXFollowers = Math.log(XFollowers + 1);
      const descriptionLength2 = Math.pow(descriptionLength, 2);
      const descriptionLength3 = Math.pow(descriptionLength, 3);
      const descriptionLength4 = Math.pow(descriptionLength, 4);
      const logXFollowers2 = Math.pow(logXFollowers, 2);
      const logXFollowers3 = Math.pow(logXFollowers, 3);
      const logXFollowers4 = Math.pow(logXFollowers, 4);
      const XFollows05 = Math.sqrt(XFollows);
  
      const resultado = intercept +
                      coef_profilePic * profilePic +
                      coef_numsLengthUsername * numsLengthUsername +
                      coef_nameUsername * nameUsername +
                      coef_descriptionLength * descriptionLength +
                      coef_externalURL * externalURL +
                      coef_descriptionLength2 * descriptionLength2 +
                      coef_descriptionLength3 * descriptionLength3 +
                      coef_descriptionLength4 * descriptionLength4 +
                      coef_logXFollowers * logXFollowers +
                      coef_logXFollowers2 * logXFollowers2 +
                    coef_logXFollowers3 * logXFollowers3 +
                    coef_logXFollowers4 * logXFollowers4 +
                    coef_XFollows05 * XFollows05;
  
    const reg_bin = resultado < 0.5 ? 0 : 1;
    const prediccion = reg_bin === 0 ? "real" : "falsa";
    const color = reg_bin === 0 ? "green" : "red";
    
    document.getElementById("resultado").innerHTML = "<h3>La cuenta es <span style='color: " + color + ";'>" + prediccion + "</span></h3>";
  }
}
  
  document.getElementById("miBoton").addEventListener("click", predecirCuenta);
</script>
```
