<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Detección de cuentas falsas de Instagram - 6&nbsp; Regresión</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./temporal_series.html" rel="next">
<link href="./formal_concept_analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./regression.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regresión</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Detección de cuentas falsas de Instagram</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exploratory_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análisis exploratorio de datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data_visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Visualización de datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./association_rules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Reglas de asociación</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./formal_concept_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">FCA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regresión</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./temporal_series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Series temporales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./other_techniques.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Otras técnicas</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./predictor.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Predictor interactivo</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Resumen</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#primeros-pasos" id="toc-primeros-pasos" class="nav-link active" data-scroll-target="#primeros-pasos"><span class="header-section-number">6.1</span> Primeros pasos</a></li>
  <li><a href="#primeras-regresiones" id="toc-primeras-regresiones" class="nav-link" data-scroll-target="#primeras-regresiones"><span class="header-section-number">6.2</span> Primeras regresiones</a></li>
  <li><a href="#preparando-el-terreno" id="toc-preparando-el-terreno" class="nav-link" data-scroll-target="#preparando-el-terreno"><span class="header-section-number">6.3</span> Preparando el terreno</a></li>
  <li><a href="#regresiones-previas" id="toc-regresiones-previas" class="nav-link" data-scroll-target="#regresiones-previas"><span class="header-section-number">6.4</span> Regresiones previas</a></li>
  <li><a href="#regresión-con-fake" id="toc-regresión-con-fake" class="nav-link" data-scroll-target="#regresión-con-fake"><span class="header-section-number">6.5</span> Regresión con fake</a></li>
  <li><a href="#mejorando-el-modelo" id="toc-mejorando-el-modelo" class="nav-link" data-scroll-target="#mejorando-el-modelo"><span class="header-section-number">6.6</span> Mejorando el modelo</a></li>
  <li><a href="#modelos-finales" id="toc-modelos-finales" class="nav-link" data-scroll-target="#modelos-finales"><span class="header-section-number">6.7</span> Modelos finales</a></li>
  <li><a href="#pruebas" id="toc-pruebas" class="nav-link" data-scroll-target="#pruebas"><span class="header-section-number">6.8</span> Pruebas</a></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones"><span class="header-section-number">6.9</span> Conclusiones</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Regresión</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>La regresión es una técnica estadística que nos permite entender y modelar la relación entre una variable dependiente (o de respuesta) y una o más variables independientes (o predictoras). En términos simples, nos ayuda a prever cómo cambia la variable dependiente cuando las variables independientes cambian.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>En el contexto de nuestro dataset de Instagram, la regresión puede ser extremadamente útil para:</p>
<p>Predecir el número de seguidores: Basándonos en variables como el número de publicaciones, la cantidad de personas a las que sigue una cuenta, la longitud de la descripción, etc. Identificar cuentas falsas: Determinando si ciertos patrones en los datos se asocian con cuentas falsas. Analizar la influencia de la privacidad: Evaluar cómo la privacidad de una cuenta afecta el número de seguidores o seguidos. Análisis de Regresión Vamos a realizar diversos análisis de regresión para explorar nuestro dataset y obtener insights valiosos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>dataset <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/train.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">attach</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="primeros-pasos" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="primeros-pasos"><span class="header-section-number">6.1</span> Primeros pasos</h2>
<p>Para las técnicas de regresión es importante que todas nuestras variables sean numéricas. No podemos hacer un ajuste con carácteres. Si fuese el caso, podríamos hacer de nuevo un trabajo de pre-processing, pero por suerte:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   576 obs. of  12 variables:
 $ profile.pic         : int  1 1 1 1 1 1 1 1 1 1 ...
 $ nums.length.username: num  0.27 0 0.1 0 0 0 0 0 0 0 ...
 $ fullname.words      : int  0 2 2 1 2 4 2 2 0 2 ...
 $ nums.length.fullname: num  0 0 0 0 0 0 0 0 0 0 ...
 $ name..username      : int  0 0 0 0 0 0 0 0 0 0 ...
 $ description.length  : int  53 44 0 82 0 81 50 0 71 40 ...
 $ external.URL        : int  0 0 0 0 0 1 0 0 0 1 ...
 $ private             : int  0 0 1 0 1 0 0 0 0 0 ...
 $ X.posts             : int  32 286 13 679 6 344 16 33 72 213 ...
 $ X.followers         : int  1000 2740 159 414 151 669987 122 1078 1824 12945 ...
 $ X.follows           : int  955 533 98 651 126 150 177 76 2713 813 ...
 $ fake                : int  0 0 0 0 0 0 0 0 0 0 ...</code></pre>
</div>
</div>
<p>¡Nuestro dataset tiene todas las variables númericas! Probablemente con regresión tengamos más juego que con FCA.</p>
<p>Aunque no todo es bueno. La variable que queremos predecir, fake, es una variable binaria, y la regresión no es lo más ideal para predecir exactamente entre dos valores.</p>
<p>Vamos a intentar sacar el mayor conocimiento de nuestros datos y encontrar ajustes interesantes.</p>
</section>
<section id="primeras-regresiones" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="primeras-regresiones"><span class="header-section-number">6.2</span> Primeras regresiones</h2>
<p>Aunque lo que queremos es predecir la variable “fake”, es bueno antes de comenzar ver relaciones entre otras variables, y particularmente que variables se relacionan más con fake.</p>
<p>En el análisis exploratorio, construimos una tabla que nos proporcionaba las mayores relaciones entre variables. Vamos a recuperar dicha tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fl">0.4</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>cor_table <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">as.table</span>(<span class="fu">cor</span>(dataset))) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Correlation =</span> Freq)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">colnames</span>(dataset)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>n_variables <span class="ot">&lt;-</span> <span class="fu">length</span>(dataset)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Para que no haya repeticiones simétricas, vamos a poner la restricción de que el </span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># orden léxicográfico de una variable sea mayor (o menor) que la otra. </span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Con un != no valdría porque habría valores filas simétricas</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>cor_table <span class="sc">%&gt;%</span> </span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">as.character</span>(Var1) <span class="sc">&gt;</span> <span class="fu">as.character</span>(Var2) <span class="sc">&amp;</span> <span class="fu">abs</span>(Correlation) <span class="sc">&gt;</span> threshold) <span class="sc">%&gt;%</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Correlation)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Var1                 Var2 Correlation
1          profile.pic                 fake  -0.6373153
2 nums.length.username                 fake   0.5876865
3         external.URL   description.length   0.4823131
4                 fake   description.length  -0.4608246
5 nums.length.username nums.length.fullname   0.4085665</code></pre>
</div>
</div>
<p>Vemos que la mayor correlación (aunque inversa, pero eso no nos importa, lo importante es que hay relación para la regresión). El problema con el que nos encontraremos más adelante, es que estas variables son binarias.</p>
<p>Podemos ir intuyendo que si queremos ajustar una variable a partir de una variable binaria, como dicha variable solo puede tomar dos valores, por muy complejo que sea el ajuste, solo hay dos posibles resultados. Como la variable que también queremos predecir es binaria, solo nos queda asignar un valor de la variable usada en el ajuste para un valor de la variable fake, pero obviamente esto no es un buen modelo.</p>
<p>Vamos a intentar hacer una regresión simple entre estas dos variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>modelo1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fake <span class="sc">~</span> profile.pic, <span class="at">data =</span> dataset)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.98837 -0.29208 -0.14023  0.01163  0.70792 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.98837    0.02943   33.58   &lt;2e-16 ***
profile.pic -0.69629    0.03514  -19.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.386 on 574 degrees of freedom
Multiple R-squared:  0.4062,    Adjusted R-squared:  0.4051 
F-statistic: 392.6 on 1 and 574 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Obtenemos un 0.40 de R^2 ajustado, lo que no está tan mal para la simplicidad del modelo.</p>
<p>Los únicos dos valores que puede dar como predicción nuestro modelo son:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(<span class="fu">predict</span>(modelo1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2920792 0.9883721</code></pre>
</div>
</div>
<p>A nosotros nos interesa un valor de 0 o un valor 1, así que podemos decir que el 0.29 es 0, por cercanía, y el 0.98 es 1. Construyamos una tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo1)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>predicciones_binarizado <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predicciones <span class="sc">&lt;</span> <span class="fl">0.3</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">profile.pic=</span>dataset<span class="sc">$</span>profile.pic,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">fake=</span>dataset<span class="sc">$</span>fake,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">prediccion=</span>predicciones,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">prediccion_bin=</span>predicciones_binarizado)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tabla, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   profile.pic fake prediccion prediccion_bin
1            1    0  0.2920792              0
2            1    0  0.2920792              0
3            1    0  0.2920792              0
4            1    0  0.2920792              0
5            1    0  0.2920792              0
6            1    0  0.2920792              0
7            1    0  0.2920792              0
8            1    0  0.2920792              0
9            1    0  0.2920792              0
10           1    0  0.2920792              0</code></pre>
</div>
</div>
<p>Si observamos lo que está pasando, es que nuestro modelo de regresión (junto a la binarización), para las cuentas con foto, predice que no es falsa, y para las cuentas sin foto, predice que es falsa.</p>
<p>Vamos a calcular el % de aciertos asumiendo lo anterior:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dataset)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>aciertos <span class="ot">&lt;-</span> <span class="fu">sum</span>(predicciones_binarizado <span class="sc">==</span> dataset<span class="sc">$</span>fake)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"Hemos obtenido un "</span>, <span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span>aciertos<span class="sc">/</span>total,<span class="dv">2</span>), <span class="st">"% de aciertos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hemos obtenido un 79.17% de aciertos"</code></pre>
</div>
</div>
<p>Parece un buen resultado, ¿verdad? Pues casi un 80% de aciertos es un buen modelo… ¿no?</p>
<p>Debemos tener en cuenta que nuestro dataset es pequeño, y que queremos un modelo riguroso, no podemos basarnos en una sola característica para predecir si una cuenta de Instagram es falsa.</p>
<p>Si concluyesemos que el modelo anterior es muy bueno, nuestro predictor se basaría simplemente en tener foto de perfil o no. Es demasiado básico. El porcentaje de aciertos viene de que en nuestro dataset esto es un patrón que suele aparecer, pero quizá si el dataset fuese mas grande, no aparecería:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>casualidades <span class="ot">&lt;-</span> <span class="fu">sum</span>(dataset<span class="sc">$</span>profile.pic <span class="sc">==</span> <span class="sc">!</span>dataset<span class="sc">$</span>fake)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> casualidades <span class="sc">/</span> total, <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 79.17</code></pre>
</div>
</div>
<p>De ahí viene el porcentaje de aciertos.</p>
<p>Y aunque el patrón siguiese dándose en un dataset más grande, es un modelo demasiado simple, no podemos ir a alguien y decirle si su cuenta es falsa o no simplemente por si tiene foto de perfil.</p>
<p>Ya que es un ajuste bidimensional, pero si lo visualizamos, para que veamos que esto por si solo no es algo muy útil:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset, <span class="fu">aes</span>(<span class="at">x =</span> profile.pic, <span class="at">y =</span> fake, <span class="at">color=</span><span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">y =</span> predicciones, <span class="at">color =</span><span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regresión lineal de fake sobre profile.pic"</span>,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"profile.pic"</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"fake"</span>) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La función lineal que nos ha creado el modelo es (donde Y es fake y X es profile.pic):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"y = "</span>, modelo1<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="st">"x + "</span>, modelo1<span class="sc">$</span>coefficients[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "y = -0.696292885102468x + 0.988372093023256"</code></pre>
</div>
</div>
</section>
<section id="preparando-el-terreno" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="preparando-el-terreno"><span class="header-section-number">6.3</span> Preparando el terreno</h2>
<p>Ya hemos visto que predecir usando únicamente variables binarizadas no es una gran opción. También hemos visto, que dado que queremos ajustar una variable binaria (fake), los resultados que queremos son 0 o 1.</p>
<p>Por lo que vamos a crear una serie de funciones con las que podamos binarizar nuestros resultados para probar nuestras predicciones, y también calcular valores estadísticos del modelo teniendo en cuenta esta binarización:</p>
<ul>
<li><strong>Función binarize.predictions</strong> Simplemente dado el conjunto de predicciones, las binariza usando cierto threshold, que por defecto será 0.5:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>binarize.predictions <span class="ot">&lt;-</span> <span class="cf">function</span>(predictions, <span class="at">threshold=</span><span class="fl">0.5</span>) {</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ifelse</span>(predictions <span class="sc">&lt;</span> <span class="fl">0.5</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Función aciertos.binarized</strong> Calcula el porcentaje de aciertos para nuestro dataset, binarizando los resultados</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>aciertos.binarized <span class="ot">&lt;-</span> <span class="cf">function</span>(predictions, real, <span class="at">threshold=</span><span class="fl">0.5</span>) {</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  total <span class="ot">&lt;-</span> <span class="fu">length</span>(real)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  aciertos <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">binarize.predictions</span>(predictions) <span class="sc">==</span> real)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span> <span class="sc">*</span> aciertos <span class="sc">/</span> total</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Función rss.binarized</strong> Calcula el RSS con las predicciones binarizadas</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>rss.binarized <span class="ot">&lt;-</span> <span class="cf">function</span>(model, real, <span class="at">threshold=</span><span class="fl">0.5</span>) {</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>((real <span class="sc">-</span> <span class="fu">binarize.predictions</span>(<span class="fu">predict</span>(model), threshold))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Función rsquared.binarized</strong> Calcula el parámetro R^2 del modelo, pero usando las predicciones binarizadas (ya que el R^2 que nos proporciona summary, se realiza con los valores sin binarizar, y es un valor diferente)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>rsquared.binarized <span class="ot">&lt;-</span> <span class="cf">function</span>(model, real, <span class="at">threshold=</span><span class="fl">0.5</span>) {</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  rss <span class="ot">&lt;-</span> <span class="fu">rss.binarized</span>(model, real, threshold)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  tss <span class="ot">&lt;-</span> <span class="fu">sum</span>((real <span class="sc">-</span> <span class="fu">mean</span>(real))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span> <span class="sc">-</span> (rss<span class="sc">/</span>tss)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Función rse.binarized</strong> Lo mismo que con rsquared.binarized, pero para calcular RSE (residual standar error):</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>rse.binarized <span class="ot">&lt;-</span> <span class="cf">function</span>(model, real, <span class="at">threshold=</span><span class="fl">0.5</span>) {</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  rss <span class="ot">&lt;-</span> <span class="fu">rss.binarized</span>(model, real, threshold)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(real)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  rse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>((<span class="dv">1</span><span class="sc">/</span>(n<span class="dv">-2</span>))<span class="sc">*</span>rss) </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(rse)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><strong>Función fstatistic.binarized</strong> Calcula el F-statistic para las predicciones binarizadas:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>fstatistic.binarized <span class="ot">&lt;-</span> <span class="cf">function</span>(model, real) {</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  tss <span class="ot">&lt;-</span> <span class="fu">sum</span>((real <span class="sc">-</span> <span class="fu">mean</span>(real))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  rss <span class="ot">&lt;-</span> <span class="fu">rss.binarized</span>(model, real, threshold)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  p <span class="ot">&lt;-</span> <span class="fu">length</span>(model<span class="sc">$</span>coefficients) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  n <span class="ot">&lt;-</span> <span class="fu">length</span>(real)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  ((tss <span class="sc">-</span> rss) <span class="sc">/</span> p) <span class="sc">/</span> (rss <span class="sc">/</span> (n <span class="sc">-</span> p <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="regresiones-previas" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="regresiones-previas"><span class="header-section-number">6.4</span> Regresiones previas</h2>
<p>Vamos a intentar ahora ajustar ahora algunas de las variables que no son binarias entre sí, a ver si encontramos alguna relación interesante.</p>
<p>Para no probar a lo loco, vamos a coger la tabla del principio pero esta vez la vamos a construir solo con variables que no sean binarias:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>unique_values <span class="ot">&lt;-</span> <span class="fu">sapply</span>(dataset, <span class="cf">function</span>(x) <span class="fu">length</span>(<span class="fu">unique</span>(x)))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>binary_vars <span class="ot">&lt;-</span> <span class="fu">names</span>(<span class="fu">which</span>(unique_values <span class="sc">==</span> <span class="dv">2</span>))</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>cor_table <span class="sc">%&gt;%</span> </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">as.character</span>(Var1) <span class="sc">&gt;</span> <span class="fu">as.character</span>(Var2) </span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>         <span class="sc">&amp;</span> <span class="sc">!</span>(Var1 <span class="sc">%in%</span> binary_vars)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>         <span class="sc">&amp;</span> <span class="sc">!</span>(Var2 <span class="sc">%in%</span> binary_vars)) <span class="sc">%&gt;%</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(Correlation)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   Var1                 Var2  Correlation
1  nums.length.username nums.length.fullname  0.408566542
2               X.posts          X.followers  0.321385480
3  nums.length.username   description.length -0.321170271
4        fullname.words   description.length  0.272522165
5             X.follows   description.length  0.226561422
6  nums.length.username       fullname.words -0.225472125
7             X.follows nums.length.username -0.172413275
8               X.posts nums.length.username -0.157442112
9               X.posts   description.length  0.144823702
10 nums.length.fullname   description.length -0.117521050
11              X.posts            X.follows  0.098225040
12            X.follows       fullname.words  0.094854964
13 nums.length.fullname       fullname.words -0.094347995
14              X.posts       fullname.words  0.073350182
15            X.follows nums.length.fullname -0.067971092
16          X.followers nums.length.username -0.062785090
17              X.posts nums.length.fullname -0.057715505
18          X.followers       fullname.words  0.033224604
19          X.followers nums.length.fullname -0.027034712
20            X.follows          X.followers -0.011065994
21          X.followers   description.length  0.005929455</code></pre>
</div>
</div>
<p>Vamos a probar una regresión con el primer par de variables, para explorar como jugar con los datos, y luego pasaremos a intentar predecir la variable fake en función de todo lo demás:</p>
<ul>
<li><strong>Regresión entre nums.length.username y nums.length.fullname</strong></li>
</ul>
<p>Primero vamos a visualizar la nube de puntos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset, <span class="fu">aes</span>(<span class="at">x=</span>nums.length.username, <span class="at">y=</span>nums.length.fullname)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se aprecia como hay muchos valores en nums.length.fullname = 0 (y = 0), y algunos en nums.length.username = 0 (x = 0) pero por lo demás, parece haber una clara tendencia lineal alcista.</p>
<p>Creamos un modelo de regresión lineal, pues salvo los valores en los ejes, parece que la nube de puntos dibuja una línea:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(nums.length.fullname <span class="sc">~</span> nums.length.username, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = nums.length.fullname ~ nums.length.username, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.21426 -0.05667  0.00303  0.00303  0.79291 

Coefficients:
                      Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)          -0.003026   0.005999  -0.504    0.614    
nums.length.username  0.238772   0.022264  10.725   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1143 on 574 degrees of freedom
Multiple R-squared:  0.1669,    Adjusted R-squared:  0.1655 
F-statistic:   115 on 1 and 574 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El R^2 es muy malo, un 0.16. Vamos a visualizar la regresión:</p>
<p>Veamos los valores predichos en una tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">nums.length.username=</span>nums.length.username,</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nums.length.fullname=</span>nums.length.fullname,</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">prediccion=</span><span class="fu">predict</span>(modelo)</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tabla, <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nums.length.username nums.length.fullname   prediccion
1                  0.27                    0  0.061442570
2                  0.00                    0 -0.003025925
3                  0.10                    0  0.020851295
4                  0.00                    0 -0.003025925
5                  0.00                    0 -0.003025925
6                  0.00                    0 -0.003025925
7                  0.00                    0 -0.003025925
8                  0.00                    0 -0.003025925
9                  0.00                    0 -0.003025925
10                 0.00                    0 -0.003025925</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset, <span class="fu">aes</span>(<span class="at">x =</span> nums.length.username, <span class="at">y =</span> nums.length.fullname, <span class="at">color=</span><span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> nums.length.username, <span class="at">y =</span> <span class="fu">predict</span>(modelo), <span class="at">color =</span><span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regresión lineal de nums.length.fullname sobre nums.length.username"</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"nums.length.username"</span>,</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"nums.length.fullname"</span>) <span class="sc">+</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Vemos que la línea se ve influenciada altamente por los valores en los ejes. Se trata de las cuentas sin números en el nombre completo pero con números en el nombre de usuario y viceversa.</p>
<p>Vamos a visualizar los gráficos que nos proporciona la función plot aplicada al modelo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-24-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-24-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-24-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La primera gráfica es simplemente un gráfico entre los residuos y los valores predichos. Vemos que R nos marca algunos valores que están muy lejanos el gráfico, estos son outliers.</p>
<p>El segundo gráfico nos muestra un gráfico nos mostraría una linea reacta si los errores se distribuyesen de manera normal, lo que claramente no es el caso. Los outliers se desvian de dicha línea, y vemos que tenemos muchos valores que se desvian bastante, probablemente los valores de los ejes.</p>
<p>La tercera gráfica también marca outliers.</p>
<p>La cuarta y última muestra la distancia de Cook, que nos indica que puntos tienen una mayor influencia en la regresión. También marca los outliers.</p>
<p>Lo que nos recomienda lo anterior es eliminar esos valores marcados, pero vamos a eliminar todos los valores de los ejes, aunque sean bastantes, para intentar encontrar una relación entre las cuentas que tienen números en el nombre de usuario y nombre real, eliminando los que no tiene números en alguno de los.</p>
<p>Eliminamos outliers:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>dataset_modif <span class="ot">&lt;-</span> dataset <span class="sc">%&gt;%</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(nums.length.username <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> nums.length.fullname <span class="sc">&gt;</span> <span class="dv">0</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dataset_modif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52</code></pre>
</div>
</div>
<p>Nos hemos quedado prácticamente con el 9% de los datos, la mayoría no tienen números en ambos nombres.</p>
<p>Vamos a realizar la predicción ahora:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(dataset_modif<span class="sc">$</span>nums.length.fullname <span class="sc">~</span> dataset_modif<span class="sc">$</span>nums.length.username, </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> dataset_modif)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = dataset_modif$nums.length.fullname ~ dataset_modif$nums.length.username, 
    data = dataset_modif)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.56406 -0.04487  0.01122  0.05000  0.23932 

Coefficients:
                                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                         0.02932    0.03803   0.771    0.444    
dataset_modif$nums.length.username  0.83109    0.08301  10.012 1.54e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.1191 on 50 degrees of freedom
Multiple R-squared:  0.6672,    Adjusted R-squared:  0.6605 
F-statistic: 100.2 on 1 and 50 DF,  p-value: 1.544e-13</code></pre>
</div>
</div>
<p>El R^2 ha subido a 0.66, pero recordamos que hemos eliminado el 91% de los datos.</p>
<p>Visualicemos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">nums.length.username=</span>dataset_modif<span class="sc">$</span>nums.length.username,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nums.length.fullname=</span>dataset_modif<span class="sc">$</span>nums.length.fullname,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">prediccion=</span><span class="fu">predict</span>(modelo)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   nums.length.username nums.length.fullname prediccion
1                  0.10                 0.10  0.1124314
2                  0.24                 0.24  0.2287844
3                  0.45                 0.25  0.4033138
4                  0.22                 0.14  0.2121625
5                  0.22                 0.22  0.2121625
6                  0.44                 0.43  0.3950029
7                  0.31                 0.36  0.2869609
8                  0.33                 0.33  0.3035827
9                  0.55                 0.29  0.4864231
10                 0.11                 0.11  0.1207423
11                 0.31                 0.31  0.2869609
12                 0.89                 0.89  0.7689946
13                 0.20                 0.20  0.1955407
14                 0.38                 0.40  0.3451374
15                 0.22                 0.22  0.2121625
16                 0.24                 0.24  0.2287844
17                 0.58                 0.36  0.5113559
18                 0.33                 0.38  0.3035827
19                 0.33                 0.33  0.3035827
20                 0.31                 0.31  0.2869609
21                 0.50                 0.33  0.4448685
22                 0.33                 0.33  0.3035827
23                 0.40                 0.40  0.3617592
24                 0.43                 0.40  0.3866920
25                 0.57                 0.40  0.5030450
26                 0.29                 0.33  0.2703390
27                 0.38                 0.33  0.3451374
28                 0.33                 0.25  0.3035827
29                 0.27                 0.27  0.2537172
30                 0.28                 0.24  0.2620281
31                 0.20                 0.33  0.1955407
32                 0.50                 0.40  0.4448685
33                 0.58                 0.44  0.5113559
34                 0.22                 0.33  0.2121625
35                 0.38                 0.33  0.3451374
36                 0.88                 1.00  0.7606837
37                 0.88                 1.00  0.7606837
38                 0.33                 0.22  0.3035827
39                 0.50                 0.50  0.4448685
40                 0.25                 0.18  0.2370953
41                 0.57                 0.57  0.5030450
42                 0.46                 0.46  0.4116248
43                 0.60                 0.50  0.5279778
44                 0.46                 0.50  0.4116248
45                 0.31                 0.31  0.2869609
46                 0.43                 0.43  0.3866920
47                 0.50                 0.40  0.4448685
48                 0.86                 0.18  0.7440619
49                 0.16                 0.12  0.1622970
50                 0.92                 1.00  0.7939274
51                 0.55                 0.44  0.4864231
52                 0.38                 0.33  0.3451374</code></pre>
</div>
</div>
<p>Y visualizamos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dataset_modif, <span class="fu">aes</span>(</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> nums.length.username, </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> nums.length.fullname, </span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">color=</span><span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> nums.length.username, </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="fu">predict</span>(modelo), </span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span><span class="st">"blue"</span>)) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regresión lineal de nums.length.fullname sobre nums.length.username"</span>,</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"nums.length.username"</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"nums.length.fullname"</span>) <span class="sc">+</span></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El ajuste es mucho mejor que el anterior, y eso que aún tenemos algún outlier como el que se ve abajo derecha.</p>
<p>Ya que hemos probado con estas dos variables estamos más que preparados para pasar a intentar predecir la variable importante, fake.</p>
</section>
<section id="regresión-con-fake" class="level2" data-number="6.5">
<h2 data-number="6.5" class="anchored" data-anchor-id="regresión-con-fake"><span class="header-section-number">6.5</span> Regresión con fake</h2>
<p>Ya hemos explorado suficiente, vamos a por lo grande.</p>
<p>Vamos a intentar predecir la variable fake a partir de las demás. Usando “.”, podemos ajustar la variable fake respecto a todas las demás. Veamos como queda dicho modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>modelo2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fake <span class="sc">~</span> ., <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ ., data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73096 -0.23729 -0.06653  0.24048  1.01052 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           7.931e-01  3.798e-02  20.880  &lt; 2e-16 ***
profile.pic          -4.380e-01  3.345e-02 -13.094  &lt; 2e-16 ***
nums.length.username  8.062e-01  7.522e-02  10.718  &lt; 2e-16 ***
fullname.words       -3.354e-02  1.333e-02  -2.516 0.012142 *  
nums.length.fullname -2.775e-02  1.212e-01  -0.229 0.818988    
name..username        2.241e-01  7.641e-02   2.933 0.003498 ** 
description.length   -1.510e-03  4.342e-04  -3.478 0.000544 ***
external.URL         -1.542e-01  4.800e-02  -3.213 0.001390 ** 
private              -9.459e-03  2.843e-02  -0.333 0.739459    
X.posts              -9.094e-05  3.570e-05  -2.547 0.011120 *  
X.followers          -9.960e-09  1.539e-08  -0.647 0.517743    
X.follows            -1.850e-05  1.499e-05  -1.235 0.217530    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3166 on 564 degrees of freedom
Multiple R-squared:  0.6074,    Adjusted R-squared:  0.5998 
F-statistic: 79.33 on 11 and 564 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Nuestro modelo tiene un 0.6 de R^2, un error residual relativamente pequeño y un f-statistic mayor de 79.33. No está nada mal.</p>
<p>Vamos a ver el % de aciertos usando las funciones que creamos al principio.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo2), fake)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 89.93056</code></pre>
</div>
</div>
<p>!Casi un 90%¡. Parece que la regresión nos está dando buenos resultados, y eso que aún no hemos intentado mejorar el modelo.</p>
<p>Calculemos el RSE, R^2 Y F-statistic estádisticos para nuestro modelo binarizado:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo2, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.3179"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo2, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.5972"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo2, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 76.03"</code></pre>
</div>
</div>
<p>Los valores de los estádisticos son prácticamente los mismos que para el modelo sin binarizar.</p>
</section>
<section id="mejorando-el-modelo" class="level2" data-number="6.6">
<h2 data-number="6.6" class="anchored" data-anchor-id="mejorando-el-modelo"><span class="header-section-number">6.6</span> Mejorando el modelo</h2>
<p>Si hacemos summary</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ ., data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73096 -0.23729 -0.06653  0.24048  1.01052 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           7.931e-01  3.798e-02  20.880  &lt; 2e-16 ***
profile.pic          -4.380e-01  3.345e-02 -13.094  &lt; 2e-16 ***
nums.length.username  8.062e-01  7.522e-02  10.718  &lt; 2e-16 ***
fullname.words       -3.354e-02  1.333e-02  -2.516 0.012142 *  
nums.length.fullname -2.775e-02  1.212e-01  -0.229 0.818988    
name..username        2.241e-01  7.641e-02   2.933 0.003498 ** 
description.length   -1.510e-03  4.342e-04  -3.478 0.000544 ***
external.URL         -1.542e-01  4.800e-02  -3.213 0.001390 ** 
private              -9.459e-03  2.843e-02  -0.333 0.739459    
X.posts              -9.094e-05  3.570e-05  -2.547 0.011120 *  
X.followers          -9.960e-09  1.539e-08  -0.647 0.517743    
X.follows            -1.850e-05  1.499e-05  -1.235 0.217530    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3166 on 564 degrees of freedom
Multiple R-squared:  0.6074,    Adjusted R-squared:  0.5998 
F-statistic: 79.33 on 11 and 564 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Vemos que tenemos varias variables con un p-value bastante alto. Estas variables añaden complejidad al modelo y no aportan nada, vamos a eliminarlas (creando un nuevo modelo sin ellas). Vamos a quedarnos con las variables que tienen un p-value menor a 0.01, es decir, profile.pic, nums.length.username, name..username, description.length y external.URL.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>modelo3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(fake <span class="sc">~</span> profile.pic <span class="sc">+</span> nums.length.username <span class="sc">+</span> name..username <span class="sc">+</span>  description.length <span class="sc">+</span> external.URL, <span class="at">data =</span> dataset)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic + nums.length.username + name..username + 
    description.length + external.URL, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.71113 -0.24453 -0.07143  0.24282  0.98317 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           0.7354681  0.0316443  23.242  &lt; 2e-16 ***
profile.pic          -0.4596554  0.0328023 -14.013  &lt; 2e-16 ***
nums.length.username  0.8445023  0.0687052  12.292  &lt; 2e-16 ***
name..username        0.2314540  0.0733411   3.156 0.001685 ** 
description.length   -0.0017381  0.0004285  -4.056 5.68e-05 ***
external.URL         -0.1731966  0.0477099  -3.630 0.000309 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3196 on 570 degrees of freedom
Multiple R-squared:  0.5956,    Adjusted R-squared:  0.592 
F-statistic: 167.9 on 5 and 570 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Vemos que el R2 ha bajado un poco pero es prácticamente el mismo, al igual que RSE, que solo ha incrementado un poco, y sin embargo, el fstatistic ha incremetnado bastante.</p>
<p>Hemos conseguido unos resultados prácticamente idénticos, mejorando el fstatistic, y reduciendo considerablemente la complejidad del modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo3), fake)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 89.93056</code></pre>
</div>
</div>
<p>Los aciertos son exactamente los mismos. Todas las variables que henmos eliminado no aportaban prácticamente nada.</p>
<p>Veamos los gráficos que nos proporciona plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-38-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-38-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="regression_files/figure-html/unnamed-chunk-38-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al estar intentando predecir una variable que solo toma dos valores, los gráficos son bastante más distintos de lo normal. Podemos apreciar que hay outliers, aunque no demasiados como cuando estabamos ajustando las variables nums.length.fullname y nums.length.username.</p>
<p>Ahora, vamos a intentar mejorar nuestro modelo añadiendo términos no lineales. Hay ciertas variables que quizá de la forma en que se nos presenta no aportan mucho a los datos, pero aplicandole alguna transformación, pueden aportar.</p>
<p>Con solo términos lineales estamos ajustando un hiperplano de a nuestra nube de puntos de n dimensiones, pero con términos no lineales formamos figuras mas complejas que un hiper plano.</p>
<p>Vamos a añadir más términos. Para la descripción vamos a añadir términos elevados a 2, 3 y 4. Para los followers, que antes nos salía que no era una variable relevante, vamos a hacerle el logaritmo, ya que los valores crecían exponencialmente (para poder hacerle el logaritmo, tenemos que tener cuidado, pues hay valores con 0, así que simplemente sumamos 1) y por último vamos a hacerle la raíz cuadrada a X.follows.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>modelo4 <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo3, . <span class="sc">~</span> . <span class="sc">+</span> </span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(description.length<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(description.length<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(description.length<span class="sc">^</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(<span class="fu">log</span>(X.followers<span class="sc">+</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(<span class="fu">log</span>(X.followers<span class="sc">+</span><span class="dv">1</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(<span class="fu">log</span>(X.followers<span class="sc">+</span><span class="dv">1</span>)<span class="sc">^</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(<span class="fu">log</span>(X.followers<span class="sc">+</span><span class="dv">1</span>)<span class="sc">^</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(<span class="fu">log</span>(X.followers<span class="sc">+</span><span class="dv">1</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>                    <span class="fu">I</span>(X.follows<span class="sc">^</span><span class="fl">0.5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Son términos “extraños” que nos hemos inventado, y como vamos a ver ahora, han provocado un ajuste bueno, pero hay que tener cuidado. Podríamos añadir todas las variables que queramos con todas las modificaciones que queramos, pero esto puede provocar un sobreajuste (overfitting).</p>
<p>El sobreajuste ocurre cuando entrenamos el modelo de forma que se adapta demasiado a los datos, sin tener ese grado de generalización que es lo que nos permite que dados nuevos datos, el modelo funcione correctamente.</p>
<p>De hecho, este último modelo, tiene cierto grado de sobreajuste, ya que hemos añadido variables que se adaptan demasiado a los datos.</p>
<p>Vamos a visualizar los estadísticos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic + nums.length.username + name..username + 
    description.length + external.URL + I(description.length^2) + 
    I(description.length^3) + I(description.length^4) + I(log(X.followers + 
    1)) + I(log(X.followers + 1)^2) + I(log(X.followers + 1)^3) + 
    I(log(X.followers + 1)^4) + I(X.follows^0.5), data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.70473 -0.18094 -0.02418  0.14988  0.82024 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                8.893e-01  5.802e-02  15.327  &lt; 2e-16 ***
profile.pic               -2.612e-01  3.073e-02  -8.498  &lt; 2e-16 ***
nums.length.username       5.798e-01  6.141e-02   9.442  &lt; 2e-16 ***
name..username             1.179e-01  6.220e-02   1.896  0.05847 .  
description.length        -1.087e-02  3.774e-03  -2.879  0.00415 ** 
external.URL              -6.688e-02  4.343e-02  -1.540  0.12412    
I(description.length^2)    2.864e-04  1.386e-04   2.067  0.03923 *  
I(description.length^3)   -3.118e-06  1.616e-06  -1.929  0.05425 .  
I(description.length^4)    1.150e-08  5.832e-09   1.972  0.04916 *  
I(log(X.followers + 1))    1.934e-01  4.927e-02   3.925 9.73e-05 ***
I(log(X.followers + 1)^2) -9.358e-02  1.450e-02  -6.455 2.33e-10 ***
I(log(X.followers + 1)^3)  9.707e-03  1.493e-03   6.501 1.76e-10 ***
I(log(X.followers + 1)^4) -2.979e-04  4.920e-05  -6.054 2.59e-09 ***
I(X.follows^0.5)           4.795e-03  1.105e-03   4.341 1.68e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2678 on 562 degrees of freedom
Multiple R-squared:   0.72, Adjusted R-squared:  0.7136 
F-statistic: 111.2 on 13 and 562 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Hemos obtenido un error residual de 0.26, un R^2 de 0.72 y un R^2 ajustado de 0.7136 (bastante cercano a 0.72, lo que indica que no tenemos mucha complejidad innecesaria, aunque). Vemos que el F-statistic si ha disminuido, a 111.2, aunque sigue siendo bastante alto.</p>
<p>Veamos el porcentaje de aciertos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>aciertos <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo4), fake)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"Hemos obtenido un "</span>, <span class="fu">round</span>(aciertos, <span class="dv">2</span>), <span class="st">"% de aciertos"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Hemos obtenido un 93.92% de aciertos"</code></pre>
</div>
</div>
<p>Casi un 94%, nada mal, pero recordemos que estos son los mismos datos con los que hemos creado el modelo.</p>
<p>Vamos a ver los estadísticos binarizados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo4, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.2469"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo4, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.7569"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo4, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 134.63"</code></pre>
</div>
</div>
<p>Son incluso mejores, y eso que estos son los reales, ya que como explicamos, nos interesan los datos binarizados, no la predicción que es resultado directo de la regresión. Parece ser que hemos encontrado un buen modelo a pesar de que nuestra predicción es binaria.</p>
<p>Vamos a pasar a la última fase, probar nuestros modelos.</p>
</section>
<section id="modelos-finales" class="level2" data-number="6.7">
<h2 data-number="6.7" class="anchored" data-anchor-id="modelos-finales"><span class="header-section-number">6.7</span> Modelos finales</h2>
<p>A modo de resumen, estos son los 4 modelos con los que nos hemos quedado (que predicen la variable fake) y a los que les haremos pruebas:</p>
<ul>
<li><strong>modelo1</strong></li>
</ul>
<p>Modelo de regresión lineal básico que simplemente usaba para predecir fake, la variable binaria profile.pic:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.98837 -0.29208 -0.14023  0.01163  0.70792 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.98837    0.02943   33.58   &lt;2e-16 ***
profile.pic -0.69629    0.03514  -19.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.386 on 574 degrees of freedom
Multiple R-squared:  0.4062,    Adjusted R-squared:  0.4051 
F-statistic: 392.6 on 1 and 574 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Estadísticos con la binarización de los resultados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo1, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.4572"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo1, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.1667"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo1, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 114.8"</code></pre>
</div>
</div>
<ul>
<li><strong>modelo2</strong></li>
</ul>
<p>Modelo de regresión generalizado usando todas las variables del dataset, al que no se le ha hecho ningún estudio ni ninguna merjora:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ ., data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.73096 -0.23729 -0.06653  0.24048  1.01052 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           7.931e-01  3.798e-02  20.880  &lt; 2e-16 ***
profile.pic          -4.380e-01  3.345e-02 -13.094  &lt; 2e-16 ***
nums.length.username  8.062e-01  7.522e-02  10.718  &lt; 2e-16 ***
fullname.words       -3.354e-02  1.333e-02  -2.516 0.012142 *  
nums.length.fullname -2.775e-02  1.212e-01  -0.229 0.818988    
name..username        2.241e-01  7.641e-02   2.933 0.003498 ** 
description.length   -1.510e-03  4.342e-04  -3.478 0.000544 ***
external.URL         -1.542e-01  4.800e-02  -3.213 0.001390 ** 
private              -9.459e-03  2.843e-02  -0.333 0.739459    
X.posts              -9.094e-05  3.570e-05  -2.547 0.011120 *  
X.followers          -9.960e-09  1.539e-08  -0.647 0.517743    
X.follows            -1.850e-05  1.499e-05  -1.235 0.217530    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3166 on 564 degrees of freedom
Multiple R-squared:  0.6074,    Adjusted R-squared:  0.5998 
F-statistic: 79.33 on 11 and 564 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Estadísticos con la binarización de los resultados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo2, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.3179"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo2, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.5972"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo2, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 76.03"</code></pre>
</div>
</div>
<ul>
<li><strong>modelo3</strong></li>
</ul>
<p>Es el modelo2 pero eliminando todas las variables que solo aportaban complejidad al modelo y prácticamente nada de información:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic + nums.length.username + name..username + 
    description.length + external.URL, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.71113 -0.24453 -0.07143  0.24282  0.98317 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           0.7354681  0.0316443  23.242  &lt; 2e-16 ***
profile.pic          -0.4596554  0.0328023 -14.013  &lt; 2e-16 ***
nums.length.username  0.8445023  0.0687052  12.292  &lt; 2e-16 ***
name..username        0.2314540  0.0733411   3.156 0.001685 ** 
description.length   -0.0017381  0.0004285  -4.056 5.68e-05 ***
external.URL         -0.1731966  0.0477099  -3.630 0.000309 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.3196 on 570 degrees of freedom
Multiple R-squared:  0.5956,    Adjusted R-squared:  0.592 
F-statistic: 167.9 on 5 and 570 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Estadísticos con la binarización de los resultados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo3, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.3179"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo3, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.5972"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo3, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 169.03"</code></pre>
</div>
</div>
<ul>
<li><strong>modelo4</strong></li>
</ul>
<p>Modelo de regresión generalizado no lineal. Resultado de añadir varaibles con logaritmos, exponentes y raices al modelo3.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = fake ~ profile.pic, data = dataset)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.98837 -0.29208 -0.14023  0.01163  0.70792 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.98837    0.02943   33.58   &lt;2e-16 ***
profile.pic -0.69629    0.03514  -19.81   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.386 on 574 degrees of freedom
Multiple R-squared:  0.4062,    Adjusted R-squared:  0.4051 
F-statistic: 392.6 on 1 and 574 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Estadísticos con la binarización de los resultados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"RSE:"</span>, <span class="fu">round</span>(<span class="fu">rse.binarized</span>(modelo4, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "RSE: 0.2469"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"R2:"</span>, <span class="fu">round</span>(<span class="fu">rsquared.binarized</span>(modelo4, fake),<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R2: 0.7569"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb104"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"F-statistic:"</span>, <span class="fu">round</span>(<span class="fu">fstatistic.binarized</span>(modelo4, fake),<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F-statistic: 134.63"</code></pre>
</div>
</div>
</section>
<section id="pruebas" class="level2" data-number="6.8">
<h2 data-number="6.8" class="anchored" data-anchor-id="pruebas"><span class="header-section-number">6.8</span> Pruebas</h2>
<p>Hasta ahora, los porcentajes de aciertos que hemos calculado, son sobre nuestro dataset de entrenamiento, es decir, usamos unos datos para crear un modelo y luego lo probamos con los mismos datos. Esto no es realista, necesitamos otros datos para probar realmente nuestro modelo.</p>
<p>Del sitio web de Kaggle, además del dataset “train.csv”, se encuentra “test.csv”. Vamos a utilizarlo para probar nuestros modelos, ya que probarlo con el mismo train.csv no es real, pues es la misma información que hemos usado para construir los modelos.</p>
<p>Importamos el dataset</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb106"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" aria-hidden="true" tabindex="-1"></a>dataset_test <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"datasets/test.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Este dataset contiene las mismas variables que train.csv:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(dataset_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "profile.pic"          "nums.length.username" "fullname.words"      
 [4] "nums.length.fullname" "name..username"       "description.length"  
 [7] "external.URL"         "private"              "X.posts"             
[10] "X.followers"          "X.follows"            "fake"                </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dataset_test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 120</code></pre>
</div>
</div>
<p>Tenemos 120 observaciones, la mitad clasificadas como falsas y la otra mitad como reales. Son observaciones distintas a las del dataset train.csv.</p>
<p>Vamos a calcular el porcentaje de aciertos en el dataset de pruebas usando cada modelo:</p>
<ul>
<li><strong>modelo1</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo1, dataset_test)</span>
<span id="cb111-2"><a href="#cb111-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-3"><a href="#cb111-3" aria-hidden="true" tabindex="-1"></a>aciertos_test <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(predicciones, dataset_test<span class="sc">$</span>fake)</span>
<span id="cb111-4"><a href="#cb111-4" aria-hidden="true" tabindex="-1"></a>aciertos_train <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo1, dataset), dataset<span class="sc">$</span>fake)</span>
<span id="cb111-5"><a href="#cb111-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb111-6"><a href="#cb111-6" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"El modelo1 ha obtenido un "</span>, <span class="fu">round</span>(aciertos_test, <span class="dv">2</span>), </span>
<span id="cb111-7"><a href="#cb111-7" aria-hidden="true" tabindex="-1"></a>       <span class="st">"% de aciertos en el dataset de pruebas"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El modelo1 ha obtenido un 74.17% de aciertos en el dataset de pruebas"</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mientras que en el dataset de entrenamiento obtuvo un 79.17% de aciertos"</code></pre>
</div>
</div>
<p>Este modelo depende totalmente de la foto de perfil. Es demasiado simple y como vemos con el test de pruebas ha perdido un 5% de aciertos. No es un buen modelo por su simplicidad y dependencia total en una única variable.</p>
<ul>
<li><strong>modelo2</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb114"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo2, dataset_test)</span>
<span id="cb114-2"><a href="#cb114-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-3"><a href="#cb114-3" aria-hidden="true" tabindex="-1"></a>aciertos_test <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(predicciones, dataset_test<span class="sc">$</span>fake)</span>
<span id="cb114-4"><a href="#cb114-4" aria-hidden="true" tabindex="-1"></a>aciertos_train <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo2, dataset), dataset<span class="sc">$</span>fake)</span>
<span id="cb114-5"><a href="#cb114-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb114-6"><a href="#cb114-6" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"El modelo2 ha obtenido un "</span>, <span class="fu">round</span>(aciertos_test, <span class="dv">2</span>), </span>
<span id="cb114-7"><a href="#cb114-7" aria-hidden="true" tabindex="-1"></a>       <span class="st">"% de aciertos en el dataset de pruebas"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El modelo2 ha obtenido un 89.17% de aciertos en el dataset de pruebas"</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mientras que en el dataset de entrenamiento obtuvo un 89.93% de aciertos"</code></pre>
</div>
</div>
<p>Resultados casi iguales. No es un mal modelo pero es mejorable, como vemos con el modelo3, ya que podemos simplificar su complejidad.</p>
<ul>
<li><strong>modelo3</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo3, dataset_test)</span>
<span id="cb117-2"><a href="#cb117-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-3"><a href="#cb117-3" aria-hidden="true" tabindex="-1"></a>aciertos_test <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(predicciones, dataset_test<span class="sc">$</span>fake)</span>
<span id="cb117-4"><a href="#cb117-4" aria-hidden="true" tabindex="-1"></a>aciertos_train <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo3, dataset), dataset<span class="sc">$</span>fake)</span>
<span id="cb117-5"><a href="#cb117-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb117-6"><a href="#cb117-6" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"El modelo3 ha obtenido un "</span>, <span class="fu">round</span>(aciertos_test, <span class="dv">2</span>), </span>
<span id="cb117-7"><a href="#cb117-7" aria-hidden="true" tabindex="-1"></a><span class="st">"% de aciertos en el dataset de pruebas"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El modelo3 ha obtenido un 89.17% de aciertos en el dataset de pruebas"</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mientras que en el dataset de entrenamiento obtuvo un 89.93% de aciertos"</code></pre>
</div>
</div>
<p>Exactamente los mismos resultados que con el modelo2, lo que nos indica que la simplificación que hemos hecho respecto al modelo2 es muy buena.</p>
<ul>
<li><strong>modelo4</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb120"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb120-1"><a href="#cb120-1" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo4, dataset_test)</span>
<span id="cb120-2"><a href="#cb120-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-3"><a href="#cb120-3" aria-hidden="true" tabindex="-1"></a>aciertos_test <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(predicciones, dataset_test<span class="sc">$</span>fake)</span>
<span id="cb120-4"><a href="#cb120-4" aria-hidden="true" tabindex="-1"></a>aciertos_train <span class="ot">&lt;-</span> <span class="fu">aciertos.binarized</span>(<span class="fu">predict</span>(modelo4, dataset), dataset<span class="sc">$</span>fake)</span>
<span id="cb120-5"><a href="#cb120-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb120-6"><a href="#cb120-6" aria-hidden="true" tabindex="-1"></a><span class="fu">paste0</span>(<span class="st">"El modelo4 ha obtenido un "</span>, <span class="fu">round</span>(aciertos_test, <span class="dv">2</span>), </span>
<span id="cb120-7"><a href="#cb120-7" aria-hidden="true" tabindex="-1"></a>       <span class="st">"% de aciertos en el dataset de pruebas"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El modelo4 ha obtenido un 93.33% de aciertos en el dataset de pruebas"</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Mientras que en el dataset de entrenamiento obtuvo un 93.92% de aciertos"</code></pre>
</div>
</div>
<p>Unos resultados muy buenos. Vemos que no tenemos mucho sobreajuste a pesar de que añadimos bastantes variables con exponentes y logaritmos. Es un buen modelo y el mejor de todos los que hemos hecho.</p>
</section>
<section id="conclusiones" class="level2" data-number="6.9">
<h2 data-number="6.9" class="anchored" data-anchor-id="conclusiones"><span class="header-section-number">6.9</span> Conclusiones</h2>
<p>Hemos explorado el la regresión como técnica estadística para modelar y predecir la veracidad o falsedad de cuentas de Instagram. A lo largo del análisis, hemos hecho múltiples regresiones.</p>
<p>Aunque la variable fake es binaria, con la regresión hemos podido aproximar su valor con cierto grado de precisión.</p>
<p>Veíamos como el primer modelo, aunque tenía un prácticamente un 80% de aciertos, era demasiado simple y no podíamos guiarnos por algo tan simple. Luego hicimos modelos más complejos y los simplificamos, hasta llegar a uno que nos daba unos valores estadísticos relativamente buenos.</p>
<p>El modelo4 ha resultado ser el mejor al incorporar términos no lineales y transformaciones logarítmicas y cuadráticas, con casi un 94% de aciertos en el dataset de entrenamiento. Aún así, este modelo mostró ciertos signos de sobreajuste (al bajar su f-statistic respecto al modelo3 mientras subía su R^2). Esto destaca la importancia de equilibrar la complejidad del modelo con su capacidad de generalización.</p>
<p>Existen otras técnicas de regresión más complejas, y otros métodos de realizar el entrenamiento, como la validación cruzada, pero en este apartado, nos hemos centrado en intentar conseguir el mejor modelo a partir de lo visto en clase.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./formal_concept_analysis.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">FCA</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./temporal_series.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Series temporales</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>